[package]
name = "rs"
version = "0.1.0"
authors = ["Jaiden Douglas <49811314+ja1den@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
